apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
    env: dev
spec:
  selector:
    matchLabels:
      app: nginx
  ports:
  - port: 80
    name: http
    tagertPort: 80
  type: ClusterIP
